# Diagnóstico preliminar da qualidade dos dados, incluindo shape, nulos, tipos e duplicados.

In [1]:
from pipelines.readers.pipelines.cvm_formulario_informacoes_trimestrais.reader_parquet import ReaderSnapshotParquet as itr

In [2]:
df = itr().read("BPA_con")

In [3]:
df.shape

(2335382, 15)

In [4]:
df.tail(3)

                   CNPJ_CIA   DT_REFER  ...  ST_CONTA_FIXA ORIGEM_FORMULARIO
2335379  97.837.181/0001-47 2026-06-30  ...              N               ITR
2335380  97.837.181/0001-47 2026-06-30  ...              N               ITR
2335381  97.837.181/0001-47 2026-06-30  ...              N               ITR

[3 rows x 15 columns]

In [5]:
df.isnull().sum()

CNPJ_CIA             0
DT_REFER             0
VERSAO               0
DENOM_CIA            0
CD_CVM               0
GRUPO_DFP            0
MOEDA                0
ESCALA_MOEDA         0
ORDEM_EXERC          0
DT_FIM_EXERC         0
CD_CONTA             0
DS_CONTA             0
VL_CONTA             0
ST_CONTA_FIXA        0
ORIGEM_FORMULARIO    0
dtype: int64

In [6]:
df.dtypes

CNPJ_CIA             string[python]
DT_REFER             datetime64[ns]
VERSAO                        Int64
DENOM_CIA            string[python]
CD_CVM               string[python]
GRUPO_DFP            string[python]
MOEDA                string[python]
ESCALA_MOEDA         string[python]
ORDEM_EXERC          string[python]
DT_FIM_EXERC         datetime64[ns]
CD_CONTA             string[python]
DS_CONTA             string[python]
VL_CONTA                    float64
ST_CONTA_FIXA        string[python]
ORIGEM_FORMULARIO            object
dtype: object

In [7]:
key_cols = df.columns.tolist()
duplicados = df[df.duplicated(subset=key_cols, keep=False)]
print(len(duplicados))

7934

In [6]:
itr(demonstration_code='DRE_con').query_parquet(filters={"CD_CVM": 16330, "CD_CONTA": "3.01"}).tail(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA,ORIGEM_FORMULARIO,INTERVALO_EXERC
7,01.547.749/0001-16,2011-09-30,1,521 PARTICIPACOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,016330,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2010-07-01,2010-09-30,3.01,Receita de Venda de Bens e/ou Serviços,452306.0,S,ITR,91
8,01.547.749/0001-16,2011-09-30,1,521 PARTICIPACOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,016330,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-09-30,3.01,Receita de Venda de Bens e/ou Serviços,395294.0,S,ITR,272
9,01.547.749/0001-16,2011-09-30,1,521 PARTICIPACOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,016330,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-07-01,2011-09-30,3.01,Receita de Venda de Bens e/ou Serviços,0.0,S,ITR,91