# Revisão inicial, filtros, observações e análise exploratória

In [ ]:
from pipelines.readers.pipelines.cvm_cias_abertas_informacao_cadastral.reader_parquet import ReaderSnapshotParquet as cias_abertas

In [3]:
df = cias_abertas().read()

In [4]:
df.tail(5)

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
2672,13.574.594/0001-96,ZAMP S.A.,ZAMP S.A.,2017-12-14,2011-04-06,NaT,<NA>,ATIVO,2017-12-14,24317,...,SP,<NA>,5501050,11,23970320,<NA>,<NA>,ri@zamp.com.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2673,71.320.931/0001-15,ZANINI SA EQUIPS PESADOS,ZANINI,1971-07-05,NaT,1997-01-27,ATENDIMENTO AS NORMAS DA INSTR CVM 03/78,CANCELADA,1997-01-27,11835,...,SP,<NA>,1013000,11,6424066,0011,<NA>,<NA>,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2674,24.744.012/0001-99,ZH OPERAÇÕES S/A,ZH OPERAÇÕES S/A,2016-09-16,2016-04-15,2017-08-07,CANCELAMENTO DE OFÍCIO,CANCELADA,2017-08-07,24007,...,SP,<NA>,4609005,011,50548989,<NA>,<NA>,renno@setaatacadista.com.br,00.115.909/0001-95,MS AUDITORES INDEPENDENTES S/C
2675,92.749.217/0001-17,ZIVI SA CUTELARIA,ZIVI S/A,1968-11-01,1931-01-01,2003-12-29,ELISÃO POR INCORPORAÇÃO,CANCELADA,2003-12-29,11843,...,RS,<NA>,91030530,51,33585109,51,33585176,michael.ceitlin@gem.ind.br,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES...
2676,74.533.787/0001-93,ZOGBI LEASING S/A ARRENDAMENTO MERCANTIL,ZOGBI LEASING,1997-09-18,1993-06-18,2004-12-23,ATENDIMENTO AS NORMAS DA INSTRUÇÃO CVM Nº 361/02,CANCELADA,2004-12-23,16462,...,<NA>,<NA>,6029900,11,36814011,11,36844630,4000.isola@bradesco.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.

In [5]:
df[["DENOM_SOCIAL", "DENOM_COMERC", "CNPJ_CIA", "CD_CVM", "SIT", "MOTIVO_CANCEL"]].tail(3)

,DENOM_SOCIAL,DENOM_COMERC,CNPJ_CIA,CD_CVM,SIT,MOTIVO_CANCEL
2674,ZH OPERAÇÕES S/A,ZH OPERAÇÕES S/A,24.744.012/0001-99,24007,CANCELADA,CANCELAMENTO DE OFÍCIO
2675,ZIVI SA CUTELARIA,ZIVI S/A,92.749.217/0001-17,11843,CANCELADA,ELISÃO POR INCORPORAÇÃO
2676,ZOGBI LEASING S/A ARRENDAMENTO MERCANTIL,ZOGBI LEASING,74.533.787/0001-93,16462,CANCELADA,ATENDIMENTO AS NORMAS DA INSTRUÇÃO CVM Nº 361/02

In [6]:
cols = ["DENOM_SOCIAL", "DENOM_COMERC", "CNPJ_CIA", "CD_CVM", "SIT", "MOTIVO_CANCEL"]

df_cias_ativo = df[df["SIT"] == "ATIVO"]

In [7]:
df_cias_ativo[cols]

,DENOM_SOCIAL,DENOM_COMERC,CNPJ_CIA,CD_CVM,SIT,MOTIVO_CANCEL
2,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,01.547.749/0001-16,16330,ATIVO,<NA>
3,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,01.851.771/0001-55,16284,ATIVO,<NA>
13,ACO VERDE DO BRASIL S.A,AÃO VERDE DO BRASIL S.A,07.636.657/0001-99,26425,ATIVO,<NA>
28,AEGEA SANEAMENTO E PARTICIPAÇÕES S.A.,AEGEA SANEAMENTO E PARTICIPAÇÕES S.A.,08.827.501/0001-58,23396,ATIVO,<NA>
29,AERIS IND. E COM. DE EQUIP. PARA GER. DE ENG. ...,<NA>,12.528.708/0001-07,25283,ATIVO,<NA>
...,...,...,...,...,...,...
2666,YBYRA CAPITAL S.A,ALEF S/A,02.217.319/0001-07,16705,ATIVO,<NA>
2667,YDUQS PARTICIPACOES S.A.,ESTACIO PARTICIPAÇÕES SA,08.807.432/0001-10,21016,ATIVO,<NA>
2668,YDUQS PARTICIPACOES S.A.,ESTACIO PARTICIPAÇÕES SA,08.807.432/0001-10,21016,ATIVO,<NA>
2669,YOU INC INCORPORADORA E PARTICIPAÇÃO S.A,YOU INC INCORPORADORA E PARTICIPAÇÕES S.A.,11.284.204/0001-18,23604,ATIVO,<NA>
2672,ZAMP S.A.,ZAMP S.A.,13.574.594/0001-96,24317,ATIVO,<NA>

In [8]:
print(len(df_cias_ativo))

757

In [9]:
df[["SIT"]].value_counts()

SIT
CANCELADA                    1912
ATIVO                         757
SUSPENSO(A) - DECISÃO ADM       8
Name: count, dtype: int64

In [10]:
df[df["CNPJ_CIA"] == "01.547.749/0001-16"]

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
2,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,1996-07-30,NaT,<NA>,ATIVO,1997-07-11,16330,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,02.878.522/0001-16,IRKO HIRASHIMA AUDITORES INDEPENDENTES LTDA.

In [12]:
df[df["CD_CVM"] == "21032"]

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
71,71.208.516/0001-74,ALGAR TELECOM S/A,CTBC TELECOM,2007-07-27,2004-01-01,NaT,<NA>,ATIVO,2007-07-27,21032,...,<NA>,<NA>,38400668,34,32562155,<NA>,<NA>,ri@algar.com.br,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.